name: stock
description: "Stock management."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  awesome_snackbar_content: ^0.1.3
  flutter_animate: ^4.2.0+1
  comment_tree: ^0.3.0
  get: ^4.6.6
  responsive_sizer: ^3.2.0
  flutter_animated_button: ^2.0.3
  animated_button: ^0.2.0
  font_awesome_flutter: ^10.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/